modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="Example Mod"
authors="Cout970"
description=""

[[mods]]
modId="simple_item"
version="${file.jarVersion}"
displayName="Simple item with custom 3D model"
authors="Cout970"
description=""

[[mods]]
modId="simple_block"
version="${file.jarVersion}"
displayName="Simple block with custom 3D model"
authors="Cout970"
description=""

[[mods]]
modId="rotable_block"
version="${file.jarVersion}"
displayName="Block with horizontal orientation"
authors="Cout970"
description=""

[[mods]]
modId="tile_block"
version="${file.jarVersion}"
displayName="Block with TileEntityRenderer"
authors="Cout970"
description=""

[[mods]]
modId="animated_block"
version="${file.jarVersion}"
displayName="Block animation"
authors="Cout970"
description=""

#[[mods]]
#modId="animated_item"
#version="${file.jarVersion}"
#displayName="Item animation"
#authors="Cout970"
#description=""

[[dependencies.examplemod]] #mandatory
    modId="modelloader" #mandatory
    mandatory=true #mandatory
    versionRange="[2.0.0,)" #mandatory
    side="CLIENT" #mandatory

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
